UPDATE Units SET PrereqTech = 'TECH_FISHING' WHERE Type = 'UNIT_WORKBOAT';
UPDATE Units SET PrereqTech = 'TECH_STONE_TOOLS' WHERE Type = 'UNIT_LIGHT_AXEMAN';

--UPDATE Units SET PrereqTech = 'TECH_HUNTING' WHERE Type = 'UNIT_SCOUT';
