UPDATE Units SET PrereqTech = 'TECH_FISHING' WHERE Class = 'UNITCLASS_WORKBOAT';
UPDATE Units SET PrereqTech = 'TECH_HUNTING' WHERE Class = 'UNITCLASS_SCOUT';

--UPDATE Units SET PrereqTech = 'TECH_STONE_TOOLS' WHERE Type = 'UNIT_LIGHT_AXEMAN';

--UPDATE Units SET PrereqTech = 'TECH_HUNTING' WHERE Type = 'UNIT_SCOUT';
